############################################################################
# apps/examples/icm42688_test/Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = icm_test
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 4096
MODULE    = $(CONFIG_EXAMPLES_ICM_TEST)

MAINSRC = icm_test_main.c

include $(APPDIR)/Application.mk