############################################################################
# apps/uav/lib/utils/Makefile
#
# Utility Libraries (Ring Buffers, DMA Buffers, etc.)
#
# Header-only library
############################################################################

include $(APPDIR)/Make.defs

# Header-only - no sources to compile

include $(APPDIR)/Application.mk
