############################################################################
# apps/uav/drivers/imu/icm42688p/Makefile
#
# ICM42688P IMU Driver
############################################################################

include $(APPDIR)/Make.defs

CSRCS   =
CXXSRCS = icm42688p.cpp

CXXFLAGS += -I$(APPDIR)

include $(APPDIR)/Application.mk
