############################################################################
# apps/uav/drivers/mag/bmm150/Makefile
#
# BMM150 Magnetometer Driver Build
############################################################################

include $(APPDIR)/Make.defs

CSRCS  =
CXXSRCS = bmm150.cpp

CXXFLAGS += -I$(APPDIR)

include $(APPDIR)/Application.mk
